# Pz DB 001

version: 1.0.0

# 資料根目錄
workspace: '{USERPROFILE}\Desktop\來源資料'

# 輸出結果的資料夾
output_folder: '{USERPROFILE}\Desktop\程式產出資料夾'

# 輸出樣版
template_folder: '{WORKSPACE}\輸出樣本及參數設定'

debug_text_file_output: '{OUTPUT_FOLDER}\output.txt'

# 本學期
semester: '113_1'
# 上學期
previous_semester: '112_2'

logging:
  level: DEBUG
  log_file: '{OUTPUT_FOLDER}\log-file.txt'
  format: '{time} - {level} - {message}'

meditation_class_names:
  - "日初"
  - "夜初"
  - "日中"
  - "夜中"
  - "日高"
  - "夜高"
  - "日研"
  - "夜研"

deacon_order:
  - "總學長"
  - "班務副總"
  - "法務副總"
  - "課務副總"
  - "學長"
  - "副學長"

# MySQL 資料庫連線設定
mysql:
  user: 'database_user'
  password: 'database_password'
  host: 'localhost'
  database: 'database_name'

# MS-Access 資料庫的設定
ms_access_db:
  db_file: '{WORKSPACE}\AccessDB\theAccessDb.accdb'
  target_table: 'MemberData'

# Google 試算表相關設定
google:
  # Google 試算表讀取認證用
  secret_file: 'C:/path/to/google/credential.json'
  spreadsheets:
    # 當前的班級成員
    class_members:
      semester: '113-1'
      spreadsheet_id: 'the_spreadsheet_id'
      sheet_name: 'the_sheet_name'
      header_row: 2
      fields_map:
        sn: '總序'
        studentId: '學員編號(公式)'
        className: '班級'
        classGroup: '組別'
        fullName: '姓名'
        dharmaName: '法名'
        gender: '性別'
        senior: '學長'
        deacon: '執事'
        nextClasses:
          - '學員上課班別'
          - '發心上第二班禪修班'
    # 雲端回寫的班級成員
    class_members_for_upload:
      spreadsheet_id: 'another_spreadsheet_id'
      sheet_name: 'another_spreadsheet_name'
      header_row: 1
    # 親眷朋友關係
    relationships:
      spreadsheet_id: '試算表的 Google ID'
      sheet_name: '親眷朋友關係'
      header_row: 2
      fields_map:
        'fullName': '姓名'
        'dharmaName': '法名'
        'gender': '性別'
        'studentId': '學員編號'
        'birthday': '生日末四碼'
        'phone': '行動電話末四碼'
        'relationKeys':
          - '關係代碼1'
          - '關係代碼2'
          - '關係代碼3'
          - '關係代碼4'
          - '關係代碼5'
          - '關係代碼6'

# MS Excel 的相關詋定
excel:
  # 輸出様版
  templates:
    # 介紹人電聯表
    introducer:
      spreadsheet_file: '{TEMPLATE}\介紹人電聯表範本.xlsx'
      header_row: 2
    # 初級班學長電聯表樣本
    fundamental_contact:
      spreadsheet_file: '{TEMPLATE}\初級班_學長電聯表.xlsx'
      header_row: 2
    # 非初級班學長電聯表樣本
    advanced_contact:
      spreadsheet_file: '{TEMPLATE}\非初級班_學長電聯表.xlsx'
      header_row: 2
    # 新編班資料樣本
    new_class_lineup:
      spreadsheet_file: '{TEMPLATE}\新編班資料-樣版.xlsx'
      header_row: 1
  # 新班表格様版
  post_lineup_template_folder: '{WORKSPACE}\新班表格'

  # 禪修活動調查
  meditation_activity_survey:
    spreadsheet_folder: '{WORKSPACE}\禪修活動調查'
    header_row: 2
    header_on_blank_try: 1
    page_mode: True

  # 禪修班意願調查表
  questionnaire:
    # 意願調查放置的資料夾
    spreadsheet_folder: '{WORKSPACE}\禪修班意願調查表'
    sheet_name: '意願調查彙整表'
    header_row: 2
    additional_notes:
      '按班級拆檔案': True
      '已有班級電聯註記': '由學長連絡'
  # 新的編班學長資料
  new_class_senior:
    spreadsheet_file: '{WORKSPACE}\學長電聯表\各班學長總名單.xlsx'
    header_row: 2
  # 升班調查資料
  signup_next_info:
    spreadsheet_file: '{WORKSPACE}\學長電聯表\學長調查回報-升班調查.xlsx'
    header_row: 2
  # 新班完成資料 (B 表)
  new_class_predefined_info:
    spreadsheet_file: '{WORKSPACE}\學長電聯表\新編班人工調整完成名單.xlsx'
    header_row: 1
  # 學員基本資料更新
  member_details_update:
    spreadsheet_folder: '{WORKSPACE}\學員資料更新'
    header_row: 1
  # 結業統計 (根據上課記錄）
  graduation:
    # 上課記錄
    records:
      spreadsheet_folder: '{WORKSPACE}\上課記錄'
      ignore_parenthesis: True
      header_row: 2
    # 結業標準
    standards:
      spreadsheet_file: '{TEMPLATE}\結業統計-參數設定.xlsx'
    # 輸出樣版
    template:
      spreadsheet_file: '{TEMPLATE}\結業統計-樣版.xlsx'
      header_row: 2
      data_skip_row: 1
      additional_notes:
        '圓滿結業': 'V'
        '結業在即': '保持'
        '結業預警': '補{{m}}堂可結業'
        '缺課過多': ''
    #      insert_row_after: 10
    # 禪修班結業規則
    graduation_standards:
      '21':
        # 實體 >= 10, 缺課 <=3, 實體 + 補課 >= 18
        - "V + L + ML >= 10"
        - "A + O + LL + _ <= 3"
        - "V + L + ML + M + S1 >= 18"
        - "S1 <= 6"
      '20':
        # 實體 >= 10, 缺課 <=3, 實體 + 補課 >= 17
        - "V + L + ML >= 10"
        - "A + O + LL + _ <= 3"
        - "V + L + ML + M + S1 >= 17"
        - "S1 <= 6"
      '19':
        - "V + L + ML >= 10"
        - "A + O + LL + _ <= 3"
        - "V + L + ML + M + S1 >= 16"
        - "S1 <= 6"
      '18':
        - "V + L + ML >= 9"
        - "A + O + LL + _ <= 3"
        - "V + L + ML + M + S1 >= 15"
        - "S1 <= 6"
      '17':
        - "V + L + ML >= 9"
        - "A + O + LL + _ <= 3"
        - "V + L + ML + M + S1 >= 14"
        - "S1 <= 6"
      '16':
        - "V + L + ML >= 8"
        - "A + O + LL + _ <= 3"
        - "V + L + ML + M + S1 >= 13"
        - "S1 <= 6"

qrcode:
  template_file: '{WORKSPACE}\福慧卡樣版.png'
  # QR Code 每格的大小
  qrcode_box: 13
  # QR Code 邊界要留幾格 (建議 2)
  qrcode_border: 2
  # QR Code 水平會置中於樣版, Y 軸則需要指定
  qrcode_y_axis: 440
  # 文字一般是放學員姓名，也會水平置中，文字所在 Y 軸則需要指定
  text_y_axis: 815
  # 文字使用的字型．標楷體: 'kaiu.tf', 微軟雅黑: 'msyh.ttc', 微軟正黑體: 'msjh.ttc'
  font_ttf: 'kaiu.ttf'
  # 文字的字體大小
  text_size: 84
  # 學號不會預設置中，分別要指字 x 座標及 y 座楆。用逗號區隔，如: 468, 1024
  id_coordinate: 468, 1004
  # 學號的字體大小 (字型寫在程式碼裡, 不提供調整)
  id_size: 26